name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Android Lint
      run: ./gradlew lint

    - name: Run Detekt
      run: ./gradlew detekt

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
  
  emulator:
    runs-on: macos
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2.29.0
        with:
          api-level: 24
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace
